from __future__ import annotations

from .presentation import escape_html as e

from .notifications import WEEKDAY_LABELS


def telegram_backup_page_content(conn, *, user, view: str, csrf: str, local_dt, can_operate, format_size, sanitize_chat_id, render, get_setting) -> str:
    def icon(path: str) -> str:
        return f'<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{path}</svg>'
    icons = {
        "settings": icon('<circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.8 2.8a2 2 0 0 0-2-.4A2 2 0 0 0 13 21H9a2 2 0 0 0-1.6-1.6 2 2 0 0 0-2 .4L2.6 17A2 2 0 0 0 3 15.1 2 2 0 0 0 1 13V9a2 2 0 0 0 2-1.6 2 2 0 0 0-.4-2L5.4 2.6A2 2 0 0 0 7.3 3 2 2 0 0 0 9 1h4a2 2 0 0 0 1.6 2 2 2 0 0 0 2-.4l2.8 2.8a2 2 0 0 0-.4 2A2 2 0 0 0 21 9v4a2 2 0 0 0-2 2Z"/>'),
        "send": icon('<path d="m21 3-7.4 18-4.2-7.1L3 10.5 21 3Z"/><path d="m9.4 13.9 4.1-3.8"/>'),
        "policy": icon('<path d="M5 3h14v18H5zM8 8h8M8 12h8M8 16h5"/>'),
        "queue": icon('<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'),
        "history": icon('<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l4 2"/>'),
        "topics": icon('<path d="M4 5h16v11H9l-5 4V5Z"/><path d="M8 9h8M8 12h5"/>'),
        "equipment": icon('<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>'),
        "group": icon('<circle cx="8" cy="8" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M2 21a6 6 0 0 1 12 0M14 16a5 5 0 0 1 8 4"/>'),
    }
    destinations = conn.execute("SELECT * FROM telegram_destinations WHERE deleted_at IS NULL ORDER BY name").fetchall()
    policies = conn.execute("""SELECT p.*,d.name destination_name,e.hostname,g.name group_name FROM telegram_backup_policies p
            JOIN telegram_destinations d ON d.id=p.destination_id LEFT JOIN equipment e ON e.id=p.equipment_id
            LEFT JOIN equipment_groups g ON g.id=p.group_id WHERE p.deleted_at IS NULL ORDER BY p.id DESC""").fetchall()
    items = conn.execute("""SELECT i.*,d.name destination_name,b.uuid backup_uuid,b.original_filename,e.hostname FROM telegram_backup_items i
            JOIN telegram_destinations d ON d.id=i.destination_id JOIN backups b ON b.id=i.backup_id JOIN equipment e ON e.id=i.equipment_id
            ORDER BY i.queued_at DESC LIMIT 200""").fetchall()
    mappings = conn.execute("""SELECT m.*,d.name destination_name,e.hostname,g.name group_name FROM telegram_topic_mappings m
            JOIN telegram_destinations d ON d.id=m.destination_id LEFT JOIN equipment e ON e.id=m.equipment_id
            LEFT JOIN equipment_groups g ON g.id=m.group_id ORDER BY m.id DESC""").fetchall()
    equipment = conn.execute("SELECT id,hostname FROM equipment WHERE is_active=1 ORDER BY hostname").fetchall()
    groups = conn.execute("SELECT id,name FROM equipment_groups ORDER BY name").fetchall()
    enabled = get_setting(conn, "telegram_backup_enabled", "0") == "1"
    default_destination = get_setting(conn, "telegram_backup_default_destination", "")
    max_bytes = get_setting(conn, "telegram_backup_max_file_bytes", "52428800")
    max_attempts = get_setting(conn, "telegram_backup_max_attempts", "5")
    retry_seconds = get_setting(conn, "telegram_backup_retry_base_seconds", "60")
    tab_defs = (("settings", "Configuração", "settings"), ("destinations", "Destinos", "send"), ("policies", "Políticas", "policy"), ("queue", "Fila", "queue"), ("history", "Histórico", "history"), ("topics", "Tópicos", "topics"))
    tabs = '<nav class="telegram-backup-tabs" aria-label="Seções da cópia no Telegram">' + "".join(f'<a href="/telegram-backup?view={key}" class="{"active" if view == key else ""}">{icons[icon_name]}<span>{label}</span></a>' for key,label,icon_name in tab_defs) + '</nav>'
    if view == "settings":
        options = "".join(f'''<option value="{r['id']}" {'selected' if str(r['id'])==default_destination else ''}>{e(r['name'])} · tópico {r['default_thread_id'] or 'geral'}</option>''' for r in destinations if r["is_active"] and r["use_for_backup_files"])
        no_destination = not options
        body = f'''<section class="telegram-settings-page"><header><div><span class="eyebrow">Comportamento da fila</span><h2>Envio de arquivos de backup</h2><p>Defina para onde os arquivos serão enviados e os limites de processamento.</p></div><span class="telegram-settings-state {'active' if enabled else 'inactive'}"><i></i>{'Envio habilitado' if enabled else 'Envio desabilitado'}</span></header>
        <form method="post" action="/telegram-backup/settings" class="panel telegram-settings-form"><input type="hidden" name="csrf_token" value="{csrf}">
          <section class="telegram-settings-toggle"><span>{icons['send']}</span><div><h3>Cópia automática no Telegram</h3><p>Envia uma segunda cópia sem remover ou substituir o backup local.</p></div><label class="notification-switch compact"><input type="checkbox" name="enabled" value="1" {'checked' if enabled else ''}><span><i></i></span><strong>Habilitar envio</strong></label></section>
          {f'''<aside class="telegram-settings-warning">{icons['history']}<div><strong>Nenhum destino disponível</strong><p>Cadastre e habilite um destino para arquivos antes de ativar esta integração.</p></div><a class="button secondary" href="/telegram-backup?view=destinations">Cadastrar destino</a></aside>''' if no_destination else ''}
          <section class="telegram-settings-section"><header><span>{icons['send']}</span><div><h3>Destino principal</h3><p>Destino usado quando nenhuma política mais específica for encontrada.</p></div></header><label><span>Destino padrão</span><select name="destination_id" required {'disabled' if no_destination else ''}>{options or '<option value="">Nenhum destino disponível</option>'}</select><small>O tópico Geral será usado quando o destino não tiver um tópico padrão.</small></label></section>
          <section class="telegram-settings-section telegram-delivery-limits"><header><span>{icons['settings']}</span><div><h3>Limites e novas tentativas</h3><p>Proteja a fila contra arquivos grandes e falhas persistentes.</p></div></header><div><label><span>Tamanho máximo do arquivo</span><div class="telegram-settings-unit"><input type="number" min="1" max="2048" name="max_mib" value="{max(1,int(max_bytes)//1048576)}"><b>MiB</b></div><small>Arquivos acima do limite não são anexados.</small></label><label><span>Máximo de tentativas</span><div class="telegram-settings-unit"><input type="number" min="1" max="20" name="max_attempts" value="{e(max_attempts)}"><b>vezes</b></div><small>Total antes de marcar o envio como falha.</small></label><label><span>Espera inicial</span><div class="telegram-settings-unit"><input type="number" min="1" max="86400" name="retry_seconds" value="{e(retry_seconds)}"><b>segundos</b></div><small>A espera aumenta progressivamente a cada falha.</small></label></div></section>
          <aside class="telegram-settings-note">{icons['policy']}<p><strong>As políticas têm prioridade.</strong> Regras por equipamento ou grupo podem escolher outro destino e tópico.</p></aside>
          <footer><a class="button secondary" href="/settings/notifications">Configurar bot e token</a><button type="submit" {'disabled' if no_destination else ''}>Salvar configuração</button></footer>
        </form></section>'''
    elif view == "destinations":
        destination_types = {"private": "Conversa privada", "group": "Grupo", "supergroup": "Supergrupo", "channel": "Canal"}
        rows = "".join(f'''<tr><td data-label="Destino"><div class="telegram-destination-name"><span>{icons['send']}</span><div><strong>{e(r['name'])}</strong><small>{e(destination_types.get(r['destination_type'], r['destination_type']))}</small></div></div></td><td data-label="Chat ID"><code>{e(r['chat_id'] if user['can_admin'] else sanitize_chat_id(r['chat_id']))}</code></td><td data-label="Tópico"><span class="telegram-thread-id">{f"#{r['default_thread_id']}" if r['default_thread_id'] else 'Geral'}</span></td><td data-label="Uso"><div class="telegram-destination-uses"><span class="{'active' if r['use_for_alerts'] else ''}">Alertas</span><span class="{'active' if r['use_for_backup_files'] else ''}">Arquivos</span><span class="{'active' if r['use_for_daily_summary'] or r['use_for_weekly_summary'] or r['use_for_executive_summary'] else ''}">Resumos</span></div></td><td data-label="Status"><span class="badge {'status-success' if r['is_active'] else 'status-neutral'}"><i></i>{'Ativo' if r['is_active'] else 'Inativo'}</span></td><td data-label="Teste">{f'''<form method="post" action="/telegram-backup/destinations/{r['id']}/test-file"><input type="hidden" name="csrf_token" value="{csrf}"><button class="small secondary">Enviar arquivo de teste</button></form>''' if user['can_admin'] else '<span class="muted">Somente visualização</span>'}</td></tr>''' for r in destinations)
        form = "" if not user["can_admin"] else f'''<form method="post" action="/telegram-backup/destinations" class="panel telegram-destination-form"><input type="hidden" name="csrf_token" value="{csrf}"><header><span>{icons['send']}</span><div><span class="eyebrow">Novo canal de entrega</span><h2>Novo destino Telegram</h2><p>Cadastre um grupo, canal, supergrupo ou conversa privada.</p></div></header><div class="telegram-destination-fields"><label><span>Nome do destino</span><input name="name" required maxlength="120" placeholder="Ex.: Alertas da operação"><small>Nome interno exibido nas políticas e históricos.</small></label><label><span>Tipo de conversa</span><select name="destination_type"><option value="private">Conversa privada</option><option value="group">Grupo</option><option value="supergroup">Supergrupo</option><option value="channel">Canal</option></select></label><label><span>Chat ID</span><input name="chat_id" required autocomplete="off" placeholder="Ex.: -1001234567890"><small>Grupos e canais normalmente usam um identificador iniciado por -100.</small></label><label><span>Tópico padrão</span><div class="telegram-topic-id-input"><b>#</b><input name="default_thread_id" type="number" min="1" placeholder="Opcional"></div><small>Deixe vazio para usar o tópico Geral.</small></label></div><fieldset class="telegram-destination-purpose"><legend>Usar este destino para</legend><div><label><input type="checkbox" name="alerts" value="1"><span>{icons['history']}<strong>Alertas</strong><small>Falhas e recuperações</small></span></label><label><input type="checkbox" name="daily" value="1"><span>{icons['queue']}<strong>Resumo diário</strong><small>Consolidação do dia</small></span></label><label><input type="checkbox" name="weekly" value="1"><span>{icons['policy']}<strong>Resumo semanal</strong><small>Últimos sete dias</small></span></label><label><input type="checkbox" name="executive" value="1"><span>{icons['settings']}<strong>Resumo executivo</strong><small>Atividade administrativa</small></span></label><label><input type="checkbox" name="backup_files" value="1" checked><span>{icons['send']}<strong>Arquivos de backup</strong><small>Cópia secundária</small></span></label></div></fieldset><aside>{icons['settings']}<p>O token do bot é único e permanece protegido em <a href="/settings/notifications">Configurações de Notificações</a>.</p></aside><footer><button type="reset" class="secondary">Limpar</button><button type="submit">Criar destino</button></footer></form>'''
        empty = f'''<tr><td colspan="6"><div class="telegram-topic-empty"><span>{icons['send']}</span><div><strong>Nenhum destino cadastrado</strong><p>Crie o primeiro destino para habilitar arquivos, alertas ou resumos.</p></div></div></td></tr>'''
        body = f'''<section class="telegram-destinations-page"><header class="telegram-topics-intro"><div><span class="eyebrow">Canais de entrega</span><h2>Destinos Telegram</h2><p>Gerencie onde os arquivos, alertas e resumos serão enviados.</p></div><div class="telegram-topic-metrics"><span><strong>{len(destinations)}</strong> destinos</span><span><strong>{sum(1 for item in destinations if item['is_active'])}</strong> ativos</span><span><strong>{sum(1 for item in destinations if item['use_for_backup_files'])}</strong> para arquivos</span></div></header><div class="telegram-destinations-grid">{form}<section class="panel table-panel telegram-destination-list"><header><span>{icons['send']}</span><div><h2>Destinos cadastrados</h2><p>Identificação, finalidade, estado e teste controlado.</p></div></header><div class="telegram-destination-table-wrap"><table><thead><tr><th>Destino</th><th>Chat ID</th><th>Tópico</th><th>Uso</th><th>Status</th><th>Teste</th></tr></thead><tbody>{rows or empty}</tbody></table></div></section></div></section>'''
    elif view == "policies":
        scope_labels = {"global": "Todos os equipamentos", "group": "Grupo de equipamentos", "equipment": "Equipamento específico"}
        compression_labels = {"none": "Sem compactação", "zip": "Arquivo ZIP", "gzip": "Arquivo GZIP"}
        rows = "".join(f'''<tr><td data-label="Destino"><div class="telegram-destination-name"><span>{icons['send']}</span><strong>{e(r['destination_name'])}</strong></div></td><td data-label="Escopo"><span class="telegram-topic-type">{e(scope_labels.get(r['scope_type'], r['scope_type']))}</span></td><td data-label="Alvo"><strong>{e(r['hostname'] or r['group_name'] or 'Todos os equipamentos')}</strong></td><td data-label="Compactação">{e(compression_labels.get(r['compression_mode'], r['compression_mode']))}</td><td data-label="Novos backups"><span class="{'telegram-policy-enabled' if r['send_new_backups'] else 'telegram-policy-disabled'}">{'Automático' if r['send_new_backups'] else 'Manual'}</span></td><td data-label="Status"><span class="badge {'status-success' if r['active'] and r['enabled'] else 'status-neutral'}"><i></i>{'Ativa' if r['active'] and r['enabled'] else 'Inativa'}</span></td></tr>''' for r in policies)
        dest_options = "".join(f"<option value='{r['id']}'>{e(r['name'])}</option>" for r in destinations if r["is_active"])
        equipment_options = "<option value=''>Nenhum</option>" + "".join(f"<option value='{r['id']}'>{e(r['hostname'])}</option>" for r in equipment)
        group_options = "<option value=''>Nenhum</option>" + "".join(f"<option value='{r['id']}'>{e(r['name'])}</option>" for r in groups)
        form = "" if not user["can_admin"] else f'''<form method="post" action="/telegram-backup/policies" class="panel telegram-policy-form" data-telegram-policy-form><input type="hidden" name="csrf_token" value="{csrf}"><header><span>{icons['policy']}</span><div><span class="eyebrow">Nova regra de envio</span><h2>Nova política</h2><p>Escolha quais backups serão copiados e como serão preparados.</p></div></header><section><h3>Destino e escopo</h3><div class="telegram-policy-fields"><label><span>Destino Telegram</span><select name="destination_id" required>{dest_options}</select></label><label><span>Aplicar a</span><select name="scope_type" data-policy-scope><option value="global">Todos os equipamentos</option><option value="group">Grupo de equipamentos</option><option value="equipment">Equipamento específico</option></select></label><label data-policy-field="group" hidden><span>Grupo de equipamentos</span><select name="group_id">{group_options}</select></label><label data-policy-field="equipment" hidden><span>Equipamento</span><select name="equipment_id">{equipment_options}</select></label><label><span>Tópico específico</span><div class="telegram-topic-id-input"><b>#</b><input name="thread_id" type="number" min="1" placeholder="Opcional"></div><small>Vazio usa a regra de tópico ou o tópico padrão.</small></label></div></section><section><h3>Arquivos e processamento</h3><div class="telegram-policy-fields"><label class="notification-switch compact"><input type="checkbox" name="all_artifacts" value="1" checked data-policy-all-files><span><i></i></span><div><strong>Todos os tipos de arquivo</strong><small>Inclui qualquer artefato elegível.</small></div></label><label data-policy-file-types hidden><span>Tipos selecionados</span><input name="file_types" placeholder="backup,rsc,cfg,txt"><small>Separe as extensões por vírgula.</small></label><label class="notification-switch compact"><input type="checkbox" name="send_new_backups" value="1" checked><span><i></i></span><div><strong>Enviar novos backups</strong><small>Enfileira automaticamente após o recebimento.</small></div></label><label><span>Compactação</span><select name="compression_mode" data-policy-compression><option value="none">Não compactar</option><option value="zip">Criar ZIP</option><option value="gzip">Criar GZIP</option></select></label><label data-policy-compression-level hidden><span>Nível de compactação</span><input name="compression_level" type="number" min="0" max="9" value="6"><small>0 é mais rápido; 9 comprime mais.</small></label></div></section><aside>{icons['settings']}<p>A cópia no Telegram é secundária. O arquivo original permanece no armazenamento local.</p></aside><footer><button type="reset" class="secondary">Limpar</button><button type="submit">Criar política</button></footer></form>'''
        empty = f'''<tr><td colspan="6"><div class="telegram-topic-empty"><span>{icons['policy']}</span><div><strong>Nenhuma política cadastrada</strong><p>Crie uma regra global ou específica para começar a copiar backups.</p></div></div></td></tr>'''
        body = f'''<section class="telegram-policies-page"><header class="telegram-topics-intro"><div><span class="eyebrow">Regras de cópia</span><h2>Políticas de envio</h2><p>Controle destino, escopo, tipos de arquivo e compactação.</p></div><div class="telegram-topic-metrics"><span><strong>{len(policies)}</strong> políticas</span><span><strong>{sum(1 for item in policies if item['active'] and item['enabled'])}</strong> ativas</span><span><strong>{sum(1 for item in policies if item['send_new_backups'])}</strong> automáticas</span></div></header><div class="telegram-policies-grid">{form}<section class="panel table-panel telegram-policy-list"><header><span>{icons['policy']}</span><div><h2>Políticas configuradas</h2><p>Destino, abrangência, preparação e estado atual.</p></div></header><div class="telegram-policy-table-wrap"><table><thead><tr><th>Destino</th><th>Escopo</th><th>Alvo</th><th>Compactação</th><th>Envio</th><th>Status</th></tr></thead><tbody>{rows or empty}</tbody></table></div></section></div></section>'''
    elif view == "topics":
        type_labels = {"equipment": "Equipamento", "group": "Grupo de equipamentos", "method": "Método de backup", "category": "Categoria", "event": "Evento"}
        rows = "".join(f'''<tr><td data-label="Destino"><div class="telegram-topic-destination"><span>{icons['send']}</span><strong>{e(r['destination_name'])}</strong></div></td><td data-label="Regra"><span class="telegram-topic-type">{e(type_labels.get(r['mapping_type'], r['mapping_type']))}</span></td><td data-label="Alvo"><strong>{e(r['hostname'] or r['group_name'] or r['match_value'] or 'Todos')}</strong></td><td data-label="Tópico"><span class="telegram-thread-id">#{r['thread_id']}</span></td><td data-label="Status"><span class="badge {'status-success' if r['is_active'] else 'status-neutral'}"><i></i>{'Ativo' if r['is_active'] else 'Inativo'}</span></td></tr>''' for r in mappings)
        dest_options = "".join(f"<option value='{r['id']}'>{e(r['name'])}</option>" for r in destinations)
        equipment_options = "<option value=''>Nenhum</option>" + "".join(f"<option value='{r['id']}'>{e(r['hostname'])}</option>" for r in equipment)
        group_options = "<option value=''>Nenhum</option>" + "".join(f"<option value='{r['id']}'>{e(r['name'])}</option>" for r in groups)
        form = "" if not user["can_admin"] else f'''<form method="post" action="/telegram-backup/topics" class="panel telegram-topic-form" data-topic-mapping-form><input type="hidden" name="csrf_token" value="{csrf}"><header><span>{icons['topics']}</span><div><span class="eyebrow">Nova regra</span><h2>Mapear tópico</h2><p>Direcione automaticamente cada mensagem para o tópico correto.</p></div></header><aside>{icons['group']}<p><strong>Grupo de equipamentos</strong> é uma organização interna do Backup Manager e não representa um grupo ou chat do Telegram.</p></aside><div class="telegram-topic-fields"><label><span>Destino Telegram</span><select name="destination_id" required>{dest_options}</select><small>Grupo, canal ou conversa que receberá a mensagem.</small></label><label><span>Aplicar a</span><select name="mapping_type" data-topic-mapping-type><option value="equipment">Equipamento específico</option><option value="group">Grupo de equipamentos</option><option value="method">Método de backup</option><option value="category">Categoria da mensagem</option><option value="event">Evento específico</option></select><small>Escolha qual condição ativa esta regra.</small></label><label data-topic-field="equipment"><span>Equipamento</span><select name="equipment_id">{equipment_options}</select></label><label data-topic-field="group" hidden><span>Grupo de equipamentos</span><select name="group_id">{group_options}</select></label><label data-topic-field="value" hidden><span data-topic-value-label>Valor da regra</span><input name="match_value" maxlength="80" placeholder="Informe o método, categoria ou evento"><small data-topic-value-help>Use o identificador operacional configurado no sistema.</small></label><label><span>ID do tópico</span><div class="telegram-topic-id-input"><b>#</b><input name="thread_id" type="number" min="1" required placeholder="Ex.: 42"></div><small>É o número do tópico mostrado pelo Telegram (`message_thread_id`).</small></label></div><footer><a class="button secondary" href="/telegram-backup?view=destinations">Revisar destinos</a><button type="submit">Salvar mapeamento</button></footer></form>'''
        empty = f'''<tr><td colspan="5"><div class="telegram-topic-empty"><span>{icons['topics']}</span><div><strong>Nenhum tópico mapeado</strong><p>Crie uma regra para separar mensagens por equipamento, grupo, método, categoria ou evento.</p></div></div></td></tr>'''
        body = f'''<section class="telegram-topics-page"><header class="telegram-topics-intro"><div><span class="eyebrow">Organização das mensagens</span><h2>Mapeamento de tópicos</h2><p>Defina regras de roteamento sem alterar o destino padrão das mensagens gerais.</p></div><div class="telegram-topic-metrics"><span><strong>{len(mappings)}</strong> regras</span><span><strong>{sum(1 for item in mappings if item['is_active'])}</strong> ativas</span><span><strong>{len(destinations)}</strong> destinos</span></div></header><div class="telegram-topics-grid">{form}<section class="panel table-panel telegram-topic-list"><header><span>{icons['topics']}</span><div><h2>Regras configuradas</h2><p>Destino, condição, alvo e tópico aplicado.</p></div></header><div class="telegram-topic-table-wrap"><table><thead><tr><th>Destino</th><th>Regra</th><th>Alvo</th><th>Tópico</th><th>Status</th></tr></thead><tbody>{rows or empty}</tbody></table></div></section></div></section>'''
    else:
        terminal = {"sent", "failed", "skipped", "cancelled"}
        visible = [r for r in items if (r["status"] not in terminal if view == "queue" else r["status"] in terminal)]
        status_labels = {"queued": "Na fila", "validating": "Validando", "preparing": "Preparando", "uploading": "Enviando", "retry_wait": "Nova tentativa agendada", "sent": "Enviado", "failed": "Falhou", "skipped": "Não enviado", "cancelled": "Cancelado"}
        error_labels = {"TELEGRAM_FILE_TOO_LARGE": "Arquivo acima do limite", "TELEGRAM_NOT_CONFIGURED": "Telegram não configurado", "TELEGRAM_THREAD_NOT_FOUND": "Tópico não encontrado", "TELEGRAM_TOPIC_CLOSED": "Tópico fechado", "TELEGRAM_FORBIDDEN": "Bot sem permissão", "TELEGRAM_UNAUTHORIZED": "Bot não autorizado", "TELEGRAM_CHAT_NOT_FOUND": "Destino não encontrado", "TELEGRAM_RATE_LIMIT": "Limite temporário do Telegram", "TELEGRAM_CONNECTION_FAILED": "Falha de conexão", "TELEGRAM_INTERNAL_ERROR": "Falha interna segura"}
        status_class = lambda value: "success" if value == "sent" else "failed" if value == "failed" else "warning" if value in {"skipped", "retry_wait"} else "neutral"
        def item_actions(item) -> str:
            if not can_operate(user): return '<span class="muted">Somente visualização</span>'
            if item["status"] in {"failed", "skipped"}: return f'''<form method="post" action="/telegram-backup/items/{item['id']}/retry"><input type="hidden" name="csrf_token" value="{csrf}"><button class="small">Tentar novamente</button></form>'''
            if item["status"] in {"queued", "retry_wait"}: return f'''<form method="post" action="/telegram-backup/items/{item['id']}/cancel"><input type="hidden" name="csrf_token" value="{csrf}"><button class="small secondary">Cancelar envio</button></form>'''
            return '<span class="muted">Nenhuma ação</span>'
        rows = "".join(f'''<tr data-telegram-item data-status="{e(r['status'])}" data-search="{e((r['hostname'] + ' ' + r['original_filename'] + ' ' + r['destination_name']).lower())}"><td data-label="Data"><time>{e(local_dt(r['queued_at']))}</time></td><td data-label="Equipamento"><strong>{e(r['hostname'])}</strong></td><td data-label="Arquivo"><div class="telegram-item-file"><span>{icons['send']}</span><div><strong title="{e(r['original_filename'])}">{e(r['original_filename'])}</strong><small>{format_size(r['bytes_total'])}</small></div></div></td><td data-label="Destino"><span>{e(r['destination_name'])}</span><small class="telegram-item-topic">{f"Tópico #{r['thread_id']}" if r['thread_id'] else 'Tópico Geral'}</small></td><td data-label="Status"><span class="telegram-item-status {status_class(r['status'])}"><i></i>{e(status_labels.get(r['status'], 'Em processamento'))}</span></td><td data-label="Tentativa"><span class="telegram-item-attempt">{r['attempt']} de {r['max_attempts']}</span></td><td data-label="Resultado"><span class="telegram-item-result {'failed' if r['error_code'] else ''}">{e(error_labels.get(r['error_code'], 'Sem falhas' if not r['error_code'] else 'Falha no processamento'))}</span>{f'''<small>Mensagem #{e(r['telegram_message_id'])}</small>''' if r['telegram_message_id'] else ''}</td><td data-label="Ação"><div class="telegram-item-actions">{item_actions(r)}</div></td></tr>''' for r in visible)
        queued_count = sum(1 for r in items if r["status"] == "queued"); retry_count = sum(1 for r in items if r["status"] == "retry_wait"); failed_count = sum(1 for r in visible if r["status"] == "failed"); sent_count = sum(1 for r in visible if r["status"] == "sent")
        title = "Fila de envios" if view == "queue" else "Histórico de envios"
        description = "Itens aguardando ou em processamento pelo worker." if view == "queue" else "Entregas concluídas, recusadas, canceladas ou com falha."
        empty_title = "Nenhum envio pendente" if view == "queue" else "Nenhum envio no histórico"
        empty_text = "A fila está livre no momento." if view == "queue" else "Os resultados aparecerão depois do primeiro processamento."
        empty = f'''<tr><td colspan="8"><div class="telegram-topic-empty"><span>{icons['queue'] if view == 'queue' else icons['history']}</span><div><strong>{empty_title}</strong><p>{empty_text}</p></div></div></td></tr>'''
        filter_options = ('<option value="">Todos os estados</option>' + "".join(f'<option value="{key}">{label}</option>' for key,label in status_labels.items() if any(r["status"] == key for r in visible)))
        body = f'''<section class="telegram-items-page" data-telegram-items-page><header class="telegram-topics-intro"><div><span class="eyebrow">Processamento de arquivos</span><h2>{title}</h2><p>{description}</p></div><div class="telegram-topic-metrics"><span><strong>{len(visible)}</strong> itens</span><span><strong>{queued_count if view == 'queue' else sent_count}</strong> {'na fila' if view == 'queue' else 'enviados'}</span><span><strong>{retry_count if view == 'queue' else failed_count}</strong> {'novas tentativas' if view == 'queue' else 'falhas'}</span></div></header><section class="panel telegram-items-panel"><header><span>{icons['queue'] if view == 'queue' else icons['history']}</span><div><h2>{title}</h2><p>Mostrando os registros mais recentes.</p></div><div class="telegram-items-filters"><label><span class="sr-only">Buscar</span><input type="search" placeholder="Buscar equipamento, arquivo ou destino" data-telegram-item-search></label><label><span class="sr-only">Estado</span><select data-telegram-item-status>{filter_options}</select></label></div></header><div class="telegram-items-table-wrap"><table><thead><tr><th>Data</th><th>Equipamento</th><th>Arquivo</th><th>Destino</th><th>Status</th><th>Tentativa</th><th>Resultado</th><th>Ação</th></tr></thead><tbody>{rows or empty}</tbody></table><div class="telegram-items-no-results" hidden data-telegram-no-results>Nenhum item corresponde aos filtros.</div></div></section></section>'''
    state = "habilitada" if enabled else "desabilitada"
    return render("Cópia de backups no Telegram", f"<section class='telegram-backup-modern'><header class='telegram-backup-hero'><span>{icons['send']}</span><div><span class='eyebrow'>Backup externo</span><h1>Cópia de backups no Telegram</h1><p>Arquivos anexados como segunda cópia. O backup local é sempre preservado.</p></div><em class='{"active" if enabled else "inactive"}'><i></i>Integração {state}</em></header>{tabs}{body}</section>", user)
